development:
    dialect: postgres
    #datasource: dbname=words-dev sslmode=disable
    datasource: dbname=words-dev host=127.0.0.1 user=dev password=secret port=5432 sslmode=disable
    dir: migrations/postgres

production:
    dialect: postgres
    datasource: dbname=words-dev sslmode=disable
    dir: migrations/postgres
