[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.3.8"

[[constraint]]
  name = "gopkg.in/godo.v2"
  version = "2.0.9"

[metadata.heroku]
  root-package = "github.com/wmsuke/WordsOfWisdom"
  go-version = "go1.11.4"
  install = [ "./..." ]
  ensure = "true"
