[prune]
  go-tests = true
  unused-packages = true

[metadata.heroku]
  root-package = "github.com/wmsuke/WordsOfWisdom"
  go-version = "go1.11.4"
  install = [ ".", "./cmd/..." ]
  ensure = "true"

[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.1.0"

[[constraint]]
  name = "github.com/go-xorm/xorm"
  version = "0.7.1"

[[constraint]]
  branch = "master"
  name = "github.com/rubenv/sql-migrate"
